github_pat: "github_pat"
queries:
  - "curl"
  - "wget"
  - "chmod"
  - "kubectl"
  - "awsp"
  - "git"
  - "gitlab"
  - "jfrog"
  - "jenkins"
  - "artifactory"
  - "ansible"
  - "helm"
  - "sonar"
  - "nslookup"
  - "history"
  - "token"
  - "secret"
  - "AWS"
  - "$Encoded"
  - "Authorization"
  - "Basic"
  - "Headers=Headers"
  - "key"
  - "base64"
  - "lanugage:yaml"
  - "language:shell"
  - "language:powershell"
  - "language:json"
  - "language:text"
  - "extension:docx"
  - "extension:pdf"
  - "extension:zip"
  - "extension:7z"
  - "extension:gz"
  - "extension:tar"
  - "extension:bak"
  - "extension:txt"
  - "extension:ini"
  - "extension:jar"
  - "extension:yml"
  - "extension:config"
